"use strict";
exports.__esModule = true;
var File_1 = require("../File");
var fileUtils_1 = require("./fileUtils");
var fileInsert_1 = require("./fileInsert");
var animalFile = new File_1.File('newAnimalFile', 'file', '/animals/testDir');
var info_1 = require("../info");
console.log("before insert array", info_1["default"]);
var afterArray = fileInsert_1.addFile(animalFile, info_1["default"]);
console.log("\n after insert array", afterArray);
console.log("\n Looking at the directory", fileUtils_1.RecursiveFindDirectory(animalFile.getLocation(), afterArray));
