"use strict";
exports.__esModule = true;
var File_1 = require("../File");
var emptyDirectory = [new File_1.File("lol", "file", "/animals/testDir", "empty file"), new File_1.File("lol2", "file", "/animals/testDir", "empty file2")];
var animals = [];
var file1 = new File_1.File("zefee", "file", "/animals", "Husky dog in Gnv");
var file2 = new File_1.File("BabyChai", "file", "/animals", "Maine coon cat in UK");
var file3 = new File_1.File("NITK", "file", "/animals", "Student");
var file4 = new File_1.File("testDir", "directory", "/animals", undefined, emptyDirectory);
animals.push(file1);
animals.push(file2);
animals.push(file3);
animals.push(file4);
exports["default"] = animals;
