"use strict";
exports.__esModule = true;
var File_1 = require("../File");
var experience = [];
var file1 = new File_1.File("vedanta", "file", "/experience", "Software Enigeer");
var file2 = new File_1.File("logicHive", "file", "/experience", "Intern");
var file3 = new File_1.File("NITK", "file", "/experience", "Student");
experience.push(file1);
experience.push(file2);
experience.push(file3);
exports["default"] = experience;
